#pragma config(Sensor, in5,    lightSensor,         sensorReflection)
#pragma config(Motor,  port7,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port6,           leftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_inch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Wait for Light -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to wait until the lights around it come up to move forward for   *|
|*  1.5 seconds.  There is a two second pause at the beginning of the program.                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions change from place to place, so the value '200' may need to be changed   *|
|*        to better suit your environment.                                                            *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 8     lightSensor         VEX Light Sensor      Mounted facing up                 *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

void stop_motor(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

};
void drive_back(){
	motor[rightMotor] = -63;			          // Motor on port2 is run at half (63) power forward
	motor[leftMotor]  = -63;
	wait1Msec(500);
};

void turn(){
			wait1Msec(1000);
			drive_back();
			stop_motor();
			motor[rightMotor] = 63;
			motor[leftMotor]  = -63;
			wait1Msec(1000);
};
void drive(){
	motor[leftMotor] = 80;
	motor[rightMotor] = 80;
};

task main(){
	while(1==1){
		while(SensorValue(lightSensor) < 300){
			while(SensorValue(sonarSensor) > 30  || SensorValue(sonarSensor) == -1){
				drive();
			}
			turn();

			}
		stop_motor();
	}

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
